### ISSUE TITLE
금융권 도입시 보안 고려사항, 출처: 금융보안원 링크 오류

### ISSUE THREAD

**Issue by jinyounghwa** [yunho0130/awesome-blockchain-kor#10]
링크가 잘못연결되었는지 404 오류가 나오고 있습니다. 
아래 부분도 링크가 연결안됀것 같습니다.

하이퍼레저 컴포저 - 스마트 컨트랙트 => 1단계: 한글 Readme.md
하이퍼레저 컴포저 - 상품 경매 네트워크 => 2단계: 한글 Readme.md

수정요청드립니다.

**Comment by yunho0130** [comment]
이슈 감사합니다. 최우선으루 수정 하겠습니다.

**Comment by yunho0130** [comment]
@jinyounghwa 수정되었습니다. 한글 성함을 알려주시면 Contributor에 업데이트 하겠습니다. 감사합니다.

**Comment by jinyounghwa** [comment]
제 이름은 진영화입니다. 감사합니다.
