### ISSUE TITLE
Please provide proper attribution for this work

### ISSUE THREAD

**Issue by gnif** [yunho0130/awesome-blockchain-kor#16]
https://stackoverflow.blog/2009/06/25/attribution-required/

https://stackoverflow.com/questions/9183178/can-php-curl-retrieve-response-headers-and-body-in-a-single-request/41135574#41135574

https://github.com/yunho0130/awesome-blockchain-kor/blob/e835d917c9d2550dc4f707869392160c59b1d929/quant-trading/ccxt-master/php/Exchange.php#L946-L960

**Comment by yunho0130** [comment]
@gnif Thanks for your issue reporting. I will open this issue to public to get some help from community.

**Comment by yunho0130** [comment]
@gnif I added attribution. Thanks for reporting it. Please see this commit bc7f04a
