### ISSUE TITLE
Window repository clone issue.

### ISSUE THREAD

**Issue by yunho0130** [yunho0130/awesome-blockchain-kor#9]

**Comment by wooqii** [comment]
![2018-06-30](https://user-images.githubusercontent.com/36095194/42121217-f994ab4a-7c65-11e8-8e69-07042182396c.png)

하이퍼렛저 패브릭쪽 파일 이름이 너무 길어서 윈도우에서는 커맨드라인과 GUI로 클론이 안되네요!

**Comment by yunho0130** [comment]
해당 폴더를 zip파일로 압축했습니다. Clone issue는 fix되었고, 이와 같은 문제를 다른 repository에서 다시 직면하게 되신다면 아래의 명령어를 CLI에서 실행해보세요. 
```git config --system core.longpaths true```
